config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get "/auth/:provider/callback" => "sessions#show"
  get 'auth/failure' => redirect('/')

  root 'users#bem'

  resources :posts, :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_save { self.email = email.downcase }
  validates :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end

  def show
    raise request.env["omniauth.auth"].to_yaml
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end


  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome"
      redirect_to @user
    else
      flash.now[:danger] = "Err"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end



  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
    @mad = session[:user_id]
  end


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "poets", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Sign up",  new_user_path %></li>
            <li><%= link_to "Log in",  login_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/bem.html.erb
<h2>Nope not this time</h2>
<div class="jumbotron"> Yet to nope you</div>
<%= link_to "Sign up",  new_user_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<%= @users %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div>
  <div>
    <%= form_for(@user) do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account"%>
    <% end %>
  </div>
  <%= link_to "Sign up with Facebook", "/auth/facebook", id: "sign_in" %>
</div>

app/views/users/show.html.erb
<h1>Show one</h1>
<%= @user.username %>
<%= @user.email %>
<%= session[:user_id] != nil %>
<p>Log out <%= link_to "Log out", logout_path, method: "delete" %></p>